version: "3.7"
services:
  mysql:
    image: mysql:5.7-debian
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=samm
      - MYSQL_USER=samm
      - MYSQL_DATABASE=samm
    ports:
      - 3306:3306
    volumes:
      - ./local_storage/mysql/data:/var/lib/mysql:rw
      - ./database/samm.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  api-server:
    image: samm-api-server:latest
    build:
      context: ./api-server
      dockerfile: Dockerfile
    environment:
      - APP_SECRET=sammysecret
      - APP_PORT=3000
      - DB_HOST=mysql
      - DB_PASS=samm
      - DB_USER=samm
      - DB_NAME=samm
    ports:
      - 3000:3000
  auth-server:
    image: samm-auth-server:latest
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    environment:
      - APP_SECRET=sammysecret
      - APP_PORT=8000
      - API_SERVER_URI=http://api-server:3000
      - DB_HOST=mysql
      - DB_PASS=samm
      - DB_USER=samm
      - DB_NAME=samm
    ports:
      - 8000:8000
  fe-server:
    image: mantisec/samm-fe-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
